- name: Jenkins installation
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Ensure Endpoint repository is installed
      yum_repository:
        name: endpoint
        description: End Point repository (required for installing Git in version 2.x)
        baseurl: https://packages.endpoint.com/rhel/$releasever/os/$basearch/
        gpgkey: https://packages.endpoint.com/endpoint-rpmsign-7.pub
        gpgcheck: yes
        enabled: yes
        state: present
    - name: Ensure Jenkins repository is installed
      yum_repository:
        name: jenkins
        description: Official Jenkins Yum Repo
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        gpgcheck: yes
        enabled: yes
        state: present
    - name: Install OpenJDK, Git and Jenkins
      yum:
        name:
          - java-1.8.0-openjdk
          - java-1.8.0-openjdk-devel
          - git
          - jenkins
        state: latest
    - name: Create directories for Jenkins
      file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
        recurse: yes
      with_items:
        - '/var/cache/jenkins/tmp'
        - '/var/cache/jenkins/heapdumps'
        - '/var/lib/jenkins/plugins'
        - '/var/lib/jenkins/jobs'
    - name: Update JENKINS_JAVA_OPTIONS
      lineinfile:
        path: "/etc/sysconfig/jenkins"
        regexp: ".*-Djava.awt.headless=true.*"
        line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Djava.io.tmpdir=/var/cache/jenkins/tmp/ -Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/Berlin -Duser.timezone=Europe/Berlin"'
        state: present
    - name: Update JENKINS_ARGS
      lineinfile:
        path: "/etc/sysconfig/jenkins"
        regexp: ".*JENKINS_ARGS=.*"
        line: 'JENKINS_ARGS="--pluginroot=/var/cache/jenkins/plugins"'
        state: present
    - name: Create limits file
      copy:
        dest: "/etc/security/limits.d/30-jenkins.conf"
        src: "/vagrant/provisioning/jenkins.conf"
    - name: Create pipelines
      copy:
        dest: "/var/lib/jenkins/jobs/"
        src: "/vagrant/provisioning/jobs/"
    - name: Download jenkins-plugin-manager
      get_url:
        url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.5.0/jenkins-plugin-manager-2.5.0.jar
        dest: /home/vagrant/jenkins-plugin-manager.jar
    - name: Copy the plugins.yaml file
      copy:
        dest: "/home/vagrant/plugins.yaml"
        src: "/vagrant/provisioning/plugins.yaml"
    - name: Copy the agent key
      copy:
        dest: "/var/lib/jenkins/agent_key"
        src: "/home/vagrant/agent_key"
        owner: jenkins
        group: jenkins
        mode: '0600'
    - name: Copy the jenkins.yaml file
      become: yes
      copy:
        dest: "/var/lib/jenkins/jenkins.yaml"
        src: "/vagrant/provisioning/jenkins.yaml"
    - name: Copy the init files
      become: yes
      copy:
        dest: "/var/lib/jenkins/init.groovy.d/"
        src: "/vagrant/provisioning/init.groovy.d/"
    - name: run the jenkins-plugin-manager
      become: yes
      command: java -jar /home/vagrant/jenkins-plugin-manager.jar --jenkins-version 2.263.4 --plugin-file /home/vagrant/plugins.yaml --plugin-download-directory /var/lib/jenkins/plugins
    - name: Update JENKINS_HOME ownership
      become: yes
      file:
        path: /var/lib/jenkins
        owner: jenkins
        group: jenkins
        state: directory
        recurse: yes
    - name: Start jenkins service
      systemd:
        name: jenkins
        state: started
